"""Cross-year (2022/2023/2024) read-only comparison of TSMC ESG pipeline outputs.

Reads only; never modifies the source CSVs. Writes two new derived files:
    outputs/cross_year_analysis.md    (human-readable report)
    outputs/cross_year_analysis.json  (structured snapshot for the app + agent tools)

Both are fully regenerated by running:  python cross_year_analysis.py

Public API (imported by src/agent_tools.py and app_pages/cross_year_panel.py):
    get_cross_year_metrics(sdg)  -> dict for one SDG (coverage / keyword shift / centroid shift)
    get_cross_year_payload()     -> full structured payload (all SDGs + consistency notes)
    load_cross_year_payload()    -> read the cached JSON if present, else compute

Produces three views:
  1. SDG coverage table (chunk counts, % of year total, 2022->2024 change)
  2. Top-15 TF-IDF keywords per SDG, three years side by side (+ persistent/new/dropped)
  3. Semantic centroid shift per SDG (2022->2023->2024), using existing embeddings
Plus a consistency-check section flagging any schema/logic differences across years.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

YEARS = ["2022", "2023", "2024"]
ROOT = Path(__file__).resolve().parent
OUT = ROOT / "outputs"
JSON_PATH = OUT / "cross_year_analysis.json"
MD_PATH = OUT / "cross_year_analysis.md"
TOP_N = 15


# ---------------------------------------------------------------------------
# Loading (read-only, cached)
# ---------------------------------------------------------------------------
@lru_cache(maxsize=None)
def _load_year(y: str):
    chunks = pd.read_csv(OUT / y / "chunks_processed.csv")
    tfidf = pd.read_csv(OUT / y / "tfidf_by_sdg.csv")
    emb = np.load(OUT / y / "chunk_embeddings.npz")["embeddings"]
    return chunks, tfidf, emb


def _exploded_sdg(chunks: pd.DataFrame) -> pd.Series:
    """Multi-label -> one row per (chunk, sdg). Returns the exploded sdg Series."""
    s = (
        chunks["sdg_labels"].fillna("").astype(str)
        .str.split(",").explode().str.strip()
    )
    return s[s != ""]


def _all_sdgs() -> list[str]:
    """The 9 formal SDG topics that appear in tfidf_by_sdg (excludes 'unclassified')."""
    sdgs: set[str] = set()
    for y in YEARS:
        sdgs |= set(_load_year(y)[1]["sdg_labels"].unique())
    return sorted(sdgs)


# ---------------------------------------------------------------------------
# Computations (pure; reused by md, json, tools, and the Streamlit panel)
# ---------------------------------------------------------------------------
def compute_consistency_notes() -> list[str]:
    notes: list[str] = []
    data = {y: _load_year(y) for y in YEARS}
    totals = {y: len(data[y][0]) for y in YEARS}

    col_sets = {y: tuple(data[y][0].columns) for y in YEARS}
    if len({col_sets[y] for y in YEARS}) == 1:
        notes.append(f"chunks_processed.csv columns are identical across all three years: {list(col_sets['2022'])}")
    else:
        notes.append("WARNING: chunks_processed.csv columns differ across years: " + str(col_sets))

    for y in YEARS:
        n_rows, (n_emb, dim) = len(data[y][0]), data[y][2].shape
        if n_rows != n_emb:
            notes.append(f"WARNING: {y}: chunk count ({n_rows}) != embedding count ({n_emb}); centroid alignment may be invalid.")
        else:
            notes.append(f"{y}: chunk count = embedding count = {n_rows}; embedding dim = {dim}.")

    sdg_sets = {y: frozenset(data[y][1]["sdg_labels"].unique()) for y in YEARS}
    if len(set(sdg_sets.values())) == 1:
        notes.append(f"tfidf_by_sdg topic set is identical across years: {len(sdg_sets['2022'])} SDGs {sorted(sdg_sets['2022'])}.")
    else:
        notes.append("WARNING: tfidf_by_sdg topic set differs across years: " + str({y: sorted(sdg_sets[y]) for y in YEARS}))

    multi = {y: int(data[y][0]["sdg_labels"].fillna("").astype(str).str.contains(",").sum()) for y in YEARS}
    notes.append(
        "sdg_labels is multi-label (comma-separated). Chunks with multiple labels: "
        + ", ".join(f"{y}={multi[y]}" for y in YEARS)
        + ". Coverage counts use label explosion (a chunk can count toward several SDGs), so per-year shares sum to > 100%."
    )

    uncl = {y: int(data[y][0]["sdg_labels"].fillna("").astype(str).str.fullmatch("unclassified").sum()) for y in YEARS}
    notes.append(
        "WARNING: schema gap: chunks_processed sdg_labels also contains an `unclassified` bucket (no SDG assigned, "
        + "never combined with other labels), but tfidf_by_sdg holds only the 9 formal SDGs with no unclassified row. "
        + "Unclassified chunks: "
        + ", ".join(f"{y}={uncl[y]}({100*uncl[y]/totals[y]:.0f}%)" for y in YEARS)
        + ". Table 1 keeps the unclassified row for reconciliation; the TF-IDF and centroid views cover only the 9 formal SDGs."
    )
    return notes


def compute_coverage() -> dict:
    """SDG coverage counts/shares per year (+ unclassified row for reconciliation)."""
    data = {y: _load_year(y) for y in YEARS}
    totals = {y: len(data[y][0]) for y in YEARS}
    exploded = {y: _exploded_sdg(data[y][0]) for y in YEARS}
    assignments = {y: int(len(exploded[y])) for y in YEARS}
    counts = {y: exploded[y].value_counts() for y in YEARS}
    all_groups = sorted(set().union(*[set(counts[y].index) for y in YEARS]))

    rows = []
    for sdg in all_groups:
        c = {y: int(counts[y].get(sdg, 0)) for y in YEARS}
        p = {y: 100 * c[y] / totals[y] for y in YEARS}
        d_abs = c["2024"] - c["2022"]
        d_pct = (d_abs / c["2022"] * 100) if c["2022"] else None
        rows.append({
            "sdg": sdg,
            "count": c,
            "share_pct": {y: round(p[y], 2) for y in YEARS},
            "delta_abs_22_24": d_abs,
            "delta_pct_22_24": (round(d_pct, 1) if d_pct is not None else None),
            "delta_share_pp_22_24": round(p["2024"] - p["2022"], 1),
        })
    return {"totals": totals, "assignments": assignments, "rows": rows}


def _top_terms(tfidf: pd.DataFrame, sdg: str, n: int = TOP_N) -> list[str]:
    g = tfidf[tfidf["sdg_labels"] == sdg].sort_values("tfidf_score", ascending=False)
    return g["term"].head(n).tolist()


def compute_keyword_shift(sdg: str, n: int = TOP_N) -> dict:
    """Top-n TF-IDF terms per year for one SDG + persistent/new/dropped tags."""
    data = {y: _load_year(y) for y in YEARS}
    terms = {y: _top_terms(data[y][1], sdg, n) for y in YEARS}
    s = {y: set(terms[y]) for y in YEARS}
    return {
        "sdg": sdg,
        "top_terms": terms,
        "persistent": sorted(s["2022"] & s["2023"] & s["2024"]),
        "new": sorted((s["2023"] | s["2024"]) - s["2022"]),
        "dropped": sorted(s["2022"] - s["2024"]),
    }


def _centroids(y: str, sdgs: list[str]) -> dict[str, np.ndarray]:
    chunks, _, emb = _load_year(y)
    labels = chunks["sdg_labels"].fillna("").astype(str)
    out: dict[str, np.ndarray] = {}
    for sdg in sdgs:
        mask = labels.apply(lambda v: sdg in [p.strip() for p in v.split(",")]).to_numpy()
        if mask.sum() > 0:
            out[sdg] = emb[mask].mean(axis=0)
    return out


def _edist(a, b) -> float:
    return float(np.linalg.norm(a - b))


def _cdist(a, b) -> float:
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    return float(1 - np.dot(a, b) / (na * nb)) if na and nb else float("nan")


def compute_centroid_shift() -> dict[str, dict]:
    """Semantic centroid displacement per SDG across 2022->2023->2024."""
    sdgs = _all_sdgs()
    cents = {y: _centroids(y, sdgs) for y in YEARS}
    out: dict[str, dict] = {}
    for sdg in sdgs:
        if all(sdg in cents[y] for y in YEARS):
            c22, c23, c24 = cents["2022"][sdg], cents["2023"][sdg], cents["2024"][sdg]
            d2223, d2324, d2224 = _edist(c22, c23), _edist(c23, c24), _edist(c22, c24)
            out[sdg] = {
                "euclid": {"d_22_23": round(d2223, 4), "d_23_24": round(d2324, 4),
                            "d_22_24_direct": round(d2224, 4), "path_total": round(d2223 + d2324, 4)},
                "cosine": {"d_22_23": round(_cdist(c22, c23), 4), "d_23_24": round(_cdist(c23, c24), 4),
                            "d_22_24_direct": round(_cdist(c22, c24), 4)},
            }
    return out


# ---------------------------------------------------------------------------
# Aggregated payloads (the public API tools/panel consume)
# ---------------------------------------------------------------------------
def get_cross_year_payload() -> dict:
    """Full structured snapshot: consistency, coverage, per-SDG keyword shift, centroid shift."""
    sdgs = _all_sdgs()
    return {
        "years": YEARS,
        "top_n": TOP_N,
        "sdgs": sdgs,
        "consistency_notes": compute_consistency_notes(),
        "coverage": compute_coverage(),
        "keyword_shift": {sdg: compute_keyword_shift(sdg) for sdg in sdgs},
        "centroid_shift": compute_centroid_shift(),
    }


def get_cross_year_metrics(sdg: str) -> dict:
    """One-SDG view stitched from coverage + keyword shift + centroid shift.

    Input: an SDG topic name (e.g. 'SDG8_labor').
    Output: that topic's three-year coverage, keyword change, and centroid displacement.
    """
    payload = load_cross_year_payload()
    sdgs = payload["sdgs"]
    if sdg not in sdgs:
        raise ValueError(f"Unknown SDG '{sdg}'. Valid options: {sdgs}")
    cov_row = next((r for r in payload["coverage"]["rows"] if r["sdg"] == sdg), None)
    return {
        "sdg": sdg,
        "years": payload["years"],
        "coverage": cov_row,
        "totals": payload["coverage"]["totals"],
        "keyword_shift": payload["keyword_shift"][sdg],
        "centroid_shift": payload["centroid_shift"].get(sdg),
    }


def load_cross_year_payload(prefer_cache: bool = True) -> dict:
    """Read the cached JSON snapshot if present (fast, demo-stable); else compute fresh."""
    if prefer_cache and JSON_PATH.exists():
        try:
            return json.loads(JSON_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    return get_cross_year_payload()


# ---------------------------------------------------------------------------
# Renderers (write derived artifacts only)
# ---------------------------------------------------------------------------
def render_markdown(payload: dict) -> str:
    YRS = payload["years"]
    cov = payload["coverage"]
    L: list[str] = []
    L.append("# TSMC ESG Cross-Year Comparison (2022 / 2023 / 2024) — Raw Reference Data\n")
    L.append("> Generated by `cross_year_analysis.py`; reads only the existing CSV/NPZ under `outputs/<year>/`. No source file is modified.\n")

    L.append("## 0. Cross-Year Consistency Checks (affect comparison validity)\n")
    L += [f"- {n}" for n in payload["consistency_notes"]]
    L.append("")

    L.append("## 1. SDG Coverage Table\n")
    L.append("Total chunks per year: " + ", ".join(f"**{y} = {cov['totals'][y]}**" for y in YRS))
    L.append("Total label assignments per year (after explosion, multi-labels counted repeatedly): "
             + ", ".join(f"{y} = {cov['assignments'][y]}" for y in YRS) + "\n")
    L.append("Counting: multi-label explosion (a chunk tagged with N SDGs adds +1 to each of N topics). Share = topic chunks / that year's total chunks, so per-year shares sum to > 100%.\n")
    L.append("| SDG topic | 2022 n | 2023 n | 2024 n | 2022 share | 2023 share | 2024 share | Δn(22→24) | Δ%(22→24) | Δshare(pp) |")
    L.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in cov["rows"]:
        c, p = r["count"], r["share_pct"]
        dpct = "—" if r["delta_pct_22_24"] is None else f"{r['delta_pct_22_24']:+.1f}%"
        L.append(f"| {r['sdg']} | {c['2022']} | {c['2023']} | {c['2024']} | "
                 f"{p['2022']:.1f}% | {p['2023']:.1f}% | {p['2024']:.1f}% | "
                 f"{r['delta_abs_22_24']:+d} | {dpct} | {r['delta_share_pp_22_24']:+.1f} |")
    L.append("")

    L.append("## 2. Top-15 TF-IDF Keywords per Topic, Three Years Side by Side\n")
    for sdg in payload["sdgs"]:
        ks = payload["keyword_shift"][sdg]
        t = ks["top_terms"]
        L.append(f"### {sdg}\n")
        L.append("| # | 2022 | 2023 | 2024 |")
        L.append("|---:|---|---|---|")
        for i in range(payload["top_n"]):
            row = [t[y][i] if i < len(t[y]) else "" for y in YRS]
            L.append(f"| {i+1} | {row[0]} | {row[1]} | {row[2]} |")
        L.append("")
        L.append(f"- **Persistent (in all three years, {len(ks['persistent'])})**: {', '.join(ks['persistent']) or '(none)'}")
        L.append(f"- **New (absent 2022, present 2023/2024, {len(ks['new'])})**: {', '.join(ks['new']) or '(none)'}")
        L.append(f"- **Dropped (present 2022, absent 2024, {len(ks['dropped'])})**: {', '.join(ks['dropped']) or '(none)'}")
        L.append("")

    L.append("## 3. Semantic Centroid Shift (2022→2023→2024)\n")
    L.append("Embedding source: each year's `chunk_embeddings.npz` (MiniLM, 384-dim, L2-normalized).")
    L.append("A topic centroid = mean embedding of all chunks tagged with that SDG in that year. Shift = Euclidean distance between adjacent-year centroids; cosine distance (1−cos) is also shown. Sorted by total path length (22→23 + 23→24), descending.\n")
    L.append("| SDG topic | d(22→23) | d(23→24) | d(22→24) direct | path total | cos(22→23) | cos(23→24) | cos(22→24) |")
    L.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    shift = payload["centroid_shift"]
    for sdg in sorted(shift, key=lambda s: shift[s]["euclid"]["path_total"], reverse=True):
        e, co = shift[sdg]["euclid"], shift[sdg]["cosine"]
        L.append(f"| {sdg} | {e['d_22_23']:.4f} | {e['d_23_24']:.4f} | {e['d_22_24_direct']:.4f} | "
                 f"{e['path_total']:.4f} | {co['d_22_23']:.4f} | {co['d_23_24']:.4f} | {co['d_22_24_direct']:.4f} |")
    L.append("")
    return "\n".join(L)


def main() -> None:
    payload = get_cross_year_payload()
    OUT.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_PATH.write_text(render_markdown(payload), encoding="utf-8")

    print("Wrote:", JSON_PATH)
    print("Wrote:", MD_PATH)
    print("\n=== consistency notes ===")
    for n in payload["consistency_notes"]:
        print(" -", n)
    print("\n=== SDG coverage (counts) ===")
    print(f"{'SDG':22} {'2022':>6} {'2023':>6} {'2024':>6} {'Δ22→24':>8} {'Δ%':>8}")
    for r in payload["coverage"]["rows"]:
        c = r["count"]
        dpct = "—" if r["delta_pct_22_24"] is None else f"{r['delta_pct_22_24']:+.1f}%"
        print(f"{r['sdg']:22} {c['2022']:>6} {c['2023']:>6} {c['2024']:>6} {r['delta_abs_22_24']:>+8} {dpct:>8}")
    print("\n=== centroid path length (desc) ===")
    shift = payload["centroid_shift"]
    for sdg in sorted(shift, key=lambda s: shift[s]["euclid"]["path_total"], reverse=True):
        e = shift[sdg]["euclid"]
        print(f"{sdg:22} path={e['path_total']:.4f}  (22→23={e['d_22_23']:.4f}, 23→24={e['d_23_24']:.4f}, 22→24直線={e['d_22_24_direct']:.4f})")


if __name__ == "__main__":
    main()
