name: textmining
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - plotly
  - scikit-learn
  - networkx
  - beautifulsoup4
  - requests
  - nltk
  - pip:
      - streamlit==1.30.0
      - wordcloud
      - pdfplumber
      - streamlit-echarts
      - pyvis
