from __future__ import annotations

"""
Compatibility keyword export built from the unified pipeline outputs.

This script exists for the older word-cloud flow, but it now reads
`outputs/chunks_processed.csv` generated by `main.py` / `src.pipeline.py`
instead of using a separate preprocessing pipeline.
"""

from pathlib import Path

import pandas as pd

from src.pipeline import build_tfidf

CHUNKS_FILE = Path("outputs/chunks_processed.csv")
OUTPUT_DIR = Path("outputs/legacy/models")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_FILE = OUTPUT_DIR / "top_keywords.csv"


def get_top_keywords(df_chunks: pd.DataFrame, top_k: int = 30) -> pd.DataFrame:
    texts = df_chunks["clean_text"].fillna("").astype(str).tolist()
    texts = [text for text in texts if text.strip()]
    if not texts:
        return pd.DataFrame(columns=["keyword", "score"])

    vectorizer, tfidf_matrix = build_tfidf(texts)
    feature_names = vectorizer.get_feature_names_out()
    scores = tfidf_matrix.mean(axis=0).A1
    top_indices = scores.argsort()[::-1][:top_k]

    records = [
        {"keyword": feature_names[i], "score": float(scores[i])}
        for i in top_indices
        if scores[i] > 0
    ]
    return pd.DataFrame(records)


def main() -> None:
    if not CHUNKS_FILE.exists():
        raise FileNotFoundError("chunks_processed.csv not found. Run `python main.py` first.")

    df_chunks = pd.read_csv(CHUNKS_FILE)
    if "clean_text" not in df_chunks.columns:
        raise ValueError("chunks_processed.csv is missing `clean_text`.")

    keyword_df = get_top_keywords(df_chunks, top_k=30)
    keyword_df.to_csv(OUTPUT_FILE, index=False)

    print("Unified keyword export complete.")
    print(f"Source dataset: {CHUNKS_FILE}")
    print(f"Saved keywords to: {OUTPUT_FILE}")
    print(keyword_df.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
